Project/Authenticate/urls.py
from django.urls import path
from .views import *
app_name = 'Authenticate'
urlpatterns = [
    path('register/', register, name="register"),
    path('login/', user_login, name="login"),
   
    
]

Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include
from Authenticate.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Authenticate.urls')),
    path('', include('blog.urls')),
    path('', include('Authenticate.api_urls')),
    path('', include('blog.api_urls')),
    path('logout/', user_logout, name="logout"),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/blog/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    # path('', home_view, name="home"),
    path('', PostList.as_view(), name="home"),
    path('create/', create_view, name="create"),
    path('<slug>', PostDetails.as_view(), name="details"),
    path('update/<slug>', PostUpdate.as_view(), name='update'),
    path('delete/<slug>', PostDelete.as_view(), name='delete'),
    
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Project/blog/models.py
from django.db import models
from Authenticate.models import *
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models import signals
from django.contrib.auth import get_user_model
from django.utils.text import slugify
    
class Post(models.Model):
    post_image = models.ImageField(upload_to='post_images', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=False, null=False)
    slug = models.SlugField(max_length=200)
    description = models.CharField(max_length = 800)
    body = RichTextField(blank=False, null=False)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    @receiver(signals.pre_save, sender="blog.Post")
    def populate_slug(sender, instance, **kwargs):
        instance.slug = slugify(instance.title)

Project/blog/forms.py
from django import forms 
from .models import *

class PostForm(forms.ModelForm):
    class Meta:
        model = Post 
        fields = ['post_image', 'title', 'description', 'body']
        widgets = {
            'post_image' : forms.ClearableFileInput(attrs={'class':'form-control w-50 mx-auto'}),
            'title': forms.TextInput(attrs={'class': 'form-control w-50 mx-auto border-t-0 border-x-0 border-orange-300'}),
            'description': forms.TextInput(attrs={'class': 'form-control mx-auto w-75 border-t-0 border-x-0 border-orange-300'}),
        }
        
        

Project/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from .models import *
from .forms import *
from django.db.models import Q
from django.urls import reverse_lazy

from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializer import *


def create_view(request):
    create_form = PostForm()
    
    if request.method == 'POST':
        create_form = PostForm(request.POST, request.FILES)
        
        if create_form.is_valid():
            instance = create_form.save(commit=False)
            instance.author = request.user
            instance.save()
            
            return redirect('blog:home')
    else:
        create_form = PostForm()
        
    context = {
        'create_form' : create_form 
    }
    return render(request, 'blog/create_post.html', context)

class PostList(ListView):
    model = Post
    context_object_name = 'posts'
    template_name= 'blog/home.html'
    ordering = 'created'
    
    def get_queryset(self):
        search = self.request.GET.get('q', '')
        multiple_search = Q(
            Q(title__icontains=search) | 
            Q(description__icontains=search) | 
            Q(author__first_name=search))
        posts = Post.objects.filter(multiple_search)
        return posts
    
    

class PostDetails(DetailView):
    model = Post
    template_name='blog/details.html'
    context_object_name = 'detail'
    
class PostUpdate(UpdateView):
    model = Post
    template_name = 'blog/create_post.html'
    fields = ['post_image', 'title', 'description', 'body']
    
class PostDelete(DeleteView):
    model = Post
    template_name = "blog/delete.html"
    success_url = reverse_lazy("blog:home")
    context_object_name = 'post'
    
    
class postApi(APIView):
    def get(self, request):
        post = Post.objects.all()
        serializer = PostSerializer(post, many=True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = PostSerializer(data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
class postApiDetail(APIView):
    def get_object(self, slug):
        Post.objects.get(slug=slug)
    
    def get(self, request, slug, format=None):
        post = self.get_object(slug)
        serializer = PostSerializer(post)
        return Response(serializer.data)
        
    def put(self, request, slug, format=None):
        post = self.get_object(slug)
        serializer = UserProfileSerializer(post, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, slug, forat=None):
        userprofile = self.get_object(slug)
        userprofile.delete 
        return Response(status=status.HTTP_204_NO_CONTENT)
    

Project/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" 
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" 
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="icon" href="{% static 'images/coolblog.png' %}">
    
    <title> {% block title %} {% endblock %} | Blog </title>
</head>
{% if user.is_authenticated %}
<body class="logged">
{% else %}
<body class="unlogged">

{% endif %}
    <header class="shadow-lg bg-blue-100">
        <nav class="nav py-3">
            {% if user.is_authenticated %}
            <a class="ml-8 text-blue-400"data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                <span class="fa-solid fa-bars text-gray-800 text-2xl"></span>
            </a>
            <a href="{% url 'blog:home' %}" class=" text-gray-800 pl-3">
                <span class="logo text-gray-900 text-2xl fa-solid fa-blog">log</span>
            </a>
            <form method="GET" class="search-bar w-25 flex">
                <div class="input-group">
                    <input type="search" name="q" placeholder="search by topic" class=" form-control">
                    <button class="searchbtn btn input-group-text" type="submit"><span class="fa-solid fa-magnifying-glass"></span></button>
                </div>
            </form>
            {% else %}
            <a href="{% url 'blog:home' %}" class="navlogo">
                <span class="px-4 text-2xl text-gray-900 hover:text-blue-400 ml-9 fa-solid fa-blog">log</span>
            </a>
            {% endif %}
            <div class="navitems text-gray-800 font-bold ">

                {% if user.is_authenticated %}
                <div class="circle mr-8 mt-1">
                <a href="{% url 'blog:create' %}"><span class="plus fa-solid fa-plus fa-bounce text-2xl"></span></a>
                </div>
                <div class="articles mx-4 mt-2">
                    <a href="#articles" class="text-gray-800 hover:text-blue-400">Articles</a>
                </div>
                <div class="btn-group mr-1 ">
                    <button type="button" class="btn ">
                        <span class="fa-solid fa-user text-blue-400"></span>
                    </button>
                    <button type="button" class="btn dropdown-toggle dropdown-toggle-split text-blue-400" data-bs-toggle="dropdown" aria-expanded="false">
                      <span class="visually-hidden">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Update Profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Create article</a></li>
                    </ul>
                </div>

                {% else %}

                <a class="navitem px-6 py-2" href="{% url 'Authenticate:login' %}">Login</a>
                <a class="navitem py-2 px-6" href="{% url 'Authenticate:register' %}">Sign Up</a>

                {% endif %}
            </div>
            </div>
        </nav>
    </header>
    <div class="side-bar offcanvas offcanvas-start bg-gray-100 text-gray-800" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header ">
          <h5 class="offcanvas-title text-3xl font-bold mx-auto" id="offcanvasExampleLabel">Blogs by Walobwa !</h5>
        </div>
        <div class="offcanvas-body text-center"> 
          <div class="btn write mx-auto">
            <a href="{% url 'blog:create' %}">Create</a>
            
          </div>
          <h3 class="font-bold mt-3 text-2xl">Topics</h3><hr>
        </div>
    </div>
    {% block content %}


    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" 
        crossorigin="anonymous"></script>
</body>
</html>

Project/blog/templates/blog/create_post.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Create Blog
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <div class="creative mt-5 pt-5 flex items-center justify-center">
        <h3 class="text-4xl font-bold text-orange-400">Get Creative! <hr></h3>
    </div>

    <div class="createform text-center pt-44">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ create_form.media }}
            {{ create_form | crispy}}
            <button class="btn bg-orange-300 text-gray-100 p-2 mt-3">Publish</button>

        </form>
    </div>
    {% endif %}
{% endblock %}

Project/blog/templates/blog/delete.html
{% extends 'blog/base.html' %}
{% block title %}
Delete
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <div class="container text-center absolute top-1/2 left-1/3 w-1/3 shadow-lg bg-gray-700 text-white rounded">
        <div class="p-3">
            <p>Are you sure you want to delete {{ post.title}}</p>
            <form method= 'POST'>
                {% csrf_token %}
            <button class="btn btn-danger">Yes</button>
            <a href="{% url 'blog:details' slug=post.slug %}" class="btn btn-success">No</a>
            </form>
        </div>
    </div>
{% endif %}
{% endblock %}

Project/blog/templates/blog/details.html
{% extends 'blog/base.html' %}
{% block title %}
{{ detail.title }}
{% endblock %}
{% block content %}

  {% if user.is_authenticated %}
  <div class="detailhead text-2xl mt-5 text-center p-5 font-bold">
    <p>{{ detail.author }}'s view on {{ detail.title }}</p>
  </div>
  <hr class=" mx-auto w-50">
  <div class="details">
    <div class="detailed shadow-lg">
      <div class="image w-100 flex justify-center bg-gray-800">
        <img src="{{ detail.post_image.url }}" class="rounded img-fluid">
      </div>
      <br>
      <div class="title">
        <h3 class="text-3xl font-bold text-center p-2">{{ detail.title }}</h3>
      </div>
      <hr class="p-3 mx-auto w-50">
      <div class="desc">
        <p class="text-center text-1xl pt-6 font-bold"> {{ detail.description }}</p>
      </div>
      <div class="body px-14">
        <p class="text-center p-5">{{ detail.body | safe }}</p>
      </div>
      {% if user.id == detail.author.id %}
      <a href="{% url 'blog:update' slug=detail.slug %}" class="btn btn-warning"><i class="fa-solid fa-pen-to-square"></i></a>
      <a href="{% url 'blog:delete' slug=detail.slug %}" class="btn btn-danger"><i class="fa-solid fa-trash"></i></a>
      {% endif %}
    </div>

  </div>
  {% endif %}

{% endblock %}

Project/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
    <section class="intro">
        <img src="{% static 'images/Directing the arrow up-rafiki.svg' %}" class="svg5">
        <p class="create-text font-bold">Click on the plus sign to write an article of your own!</p>
        <div class="intro-text">
            <p class="font-bold text-blue-400 text-4xl">Enjoy Reading or Write educative articles and blogs ...</p><br>
            <p class="font-bold">“If you want to be a writer, you must do two things above all others: read a lot and write a lot.” ― Stephen King</p>
        </div>
        <img src="{% static 'images/Knowledge-amico.svg' %}" class="svg6">
    </section>
    <hr>
    <section class="blog-cards" id="articles">
        <h3 class="text-center font-bold text-5xl mt-3">Blogs and articles</h3><hr class="w-50 mx-auto mt-3 pb-5">
        <div class="cards pt-5">
            <div class="row gx-1">
                {% for post in posts %}
                    <div class="col">
                        <div class="card shadow-lg p-2">
                            <img src="{{ post.post_image.url }}" class="card-img-top">
                            <div class="card-body">
                            <h5 class="card-title font-bold text-2xl">{{ post.title }}</h5>
                            <p class="">By: <b>{{ post.author }}</b></p>
                            <p class="card-text">{{ post.description }}</p>
                            <a href="{{ post.slug }}" class="view-art btn">View</a><br>
                            <small class="ml-2"><em>Published: {{ post.created }}</em></small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section class="footer">
        <hr>
        <footer class="foot">
            <h2 class="font-bold text-2xl">Contact me:</h2>
            <div class="contact">
                <a href="#"><img src="{% static 'images/Instagram_Box_Filled_L Shadowless.png'%}" class="ig">
                <a href="#"><img src="{% static 'images/Twitter_Mark_L Shadowless.png'%}" class="twta">
                <a href="#"><img src="{% static 'images/Linkedin_Filled_R Shadowless.png'%}" class="lnkd">
            </div>
        </footer>
    </section>
    {% else %}
    <div class="button flex items-center justify-center fa-bounce">
        <a href="{% url 'Authenticate:login' %}" class="font-bold p-9 fa-solid fa-pen-nib">Write
        </a>
    </div>
    <img src="{% static 'images/Blog post-amico (1).svg' %}" class="svg1">
    <img src="{% static 'images/Content-amico.svg' %}" class="svg2">
    <div class="landing">
        <p class="title text-blue-400 font-bold text-5xl pt-9 mt-5">AFRITECH GAZETTE </p>
        <p class="quote text-2xl pt-4 font-bold">The best time to act on this was decades ago. The second best time is now. 
            You've come to the right place, share your thoughts here by writing blogs ...
        </p>
    </div>
    {% comment %} <section class="footer">
        <footer class="foot">
            <div class="contact">
            </div>
        </footer>
    </section> {% endcomment %}
    {% endif %}

{% endblock %}